# create_batches.R
# Generate individual batch scripts for memory-safe simulation execution
#
# Strategy: 16 batches of 4 configs each (one sample size, all 4 tolerances)
# Each batch: ~400 runs, ~3-5GB peak, ~5-8 minutes

library(tools)

batch_dir <- "simulations/batches"
if (!dir.exists(batch_dir)) {
  dir.create(batch_dir, recursive = TRUE)
}

# Full simulation design
dgps <- c("dgp1", "dgp2", "dgp3", "dgp4")
ns <- c(200, 400, 800, 1600)
epsilons <- c(0.01, 0.05, 0.1, 0.2)
n_reps <- 100
tau <- 0.15
K <- 5

# Generate batch configurations
# Each batch: one DGP, one sample size, all tolerances (4 configs)
batch_configs <- expand.grid(
  dgp = dgps,
  n = ns,
  stringsAsFactors = FALSE
)

message("Creating ", nrow(batch_configs), " batch scripts...")

# Create each batch script
for (i in 1:nrow(batch_configs)) {
  dgp <- batch_configs$dgp[i]
  n <- batch_configs$n[i]

  batch_file <- file.path(batch_dir, sprintf("batch_%02d_%s_n%d.R", i, dgp, n))

  cat(sprintf('# Batch %d: %s, n=%d (4 configs)
# Auto-generated by create_batches.R

if (!requireNamespace("devtools", quietly = TRUE)) stop("devtools required")
devtools::load_all()

if (!requireNamespace("optimaltrees", quietly = TRUE)) stop("optimaltrees required")

source("simulations/run_simulations_extended.R", local = TRUE)

results_dir <- "simulations/results_extended"
if (!dir.exists(results_dir)) {
  dir.create(results_dir, recursive = TRUE)
}

message("\\n=== BATCH %d: %s, n=%d ===\\n")

# This batch configuration
dgp_name <- "%s"
n <- %d
epsilons <- c(%s)
n_reps <- %d
tau <- %.2f
K <- %d

dgp_fn <- %s

message("DGP: ", dgp_name)
message("Sample size: ", n)
message("Tolerances: ", paste(epsilons, collapse = ", "))
message("Replications per config: ", n_reps)
message("Total runs this batch: ", length(epsilons) * n_reps, "\\n")

# Track memory
initial_mem <- as.numeric(system("ps -o rss= -p $$", intern = TRUE)) / 1024
message("Initial memory: ", round(initial_mem, 1), " MB\\n")

batch_start <- Sys.time()

# Run each epsilon configuration
for (epsilon in epsilons) {
  message("\\n--- Config: epsilon = ", epsilon, " ---")

  config_start <- Sys.time()

  # Run comparison
  result <- run_comparison(
    dgp_fn = dgp_fn,
    n = n,
    K = K,
    tau = tau,
    n_reps = n_reps,
    epsilon = epsilon,
    seed_start = %d + as.integer(epsilon * 10000)
  )

  config_elapsed <- as.numeric(difftime(Sys.time(), config_start, units = "secs"))

  # Save results (metrics only, no raw results)
  result_to_save <- list(
    config = data.frame(
      dgp = dgp_name,
      n = n,
      epsilon = epsilon,
      K = K,
      tau = tau,
      n_reps = n_reps
    ),
    fold_specific = result$fold_specific,
    rashomon = result$rashomon,
    oracle = result$oracle
  )

  saveRDS(result_to_save, file.path(results_dir,
          sprintf("result_%%s_n%%d_eps%%.3f.rds", dgp_name, n, epsilon)))

  # Clear memory
  rm(result, result_to_save)
  gc(verbose = FALSE)

  current_mem <- as.numeric(system("ps -o rss= -p $$", intern = TRUE)) / 1024
  message(sprintf("  Config completed in %%.1f sec", config_elapsed))
  message(sprintf("  Current memory: %%.1f MB (delta: %%.1f MB)",
                 current_mem, current_mem - initial_mem))
}

batch_elapsed <- as.numeric(difftime(Sys.time(), batch_start, units = "mins"))
final_mem <- as.numeric(system("ps -o rss= -p $$", intern = TRUE)) / 1024

message("\\n=== BATCH %d COMPLETE ===")
message("Batch time: ", round(batch_elapsed, 2), " minutes")
message("Final memory: ", round(final_mem, 1), " MB")
message("Memory increase: ", round(final_mem - initial_mem, 1), " MB\\n")
',
    i, dgp, n,
    i, dgp, n,
    dgp,
    n,
    paste(sprintf("%.2f", epsilons), collapse = ", "),
    n_reps,
    tau,
    K,
    paste0("generate_data_", dgp),
    i * 10000,
    i
  ), file = batch_file)

  message("  Created: ", basename(batch_file))
}

message("\n=== Batch Scripts Created ===")
message("Total batches: ", nrow(batch_configs))
message("Location: ", batch_dir)
message("\nTo run all batches sequentially:")
message("  Rscript simulations/run_all_batches.R")
message("\nOr run individual batches:")
message("  Rscript simulations/batches/batch_01_dgp1_n200.R")
