# Batch 5: dgp1, n=400 (4 configs)
# Auto-generated by create_batches.R

if (!requireNamespace("devtools", quietly = TRUE)) stop("devtools required")
devtools::load_all()

if (!requireNamespace("optimaltrees", quietly = TRUE)) stop("optimaltrees required")

source("simulations/run_simulations_extended.R", local = TRUE)

results_dir <- "simulations/results_extended"
if (!dir.exists(results_dir)) {
  dir.create(results_dir, recursive = TRUE)
}

message("\n=== BATCH 5: dgp1, n=400 ===\n")

# This batch configuration
dgp_name <- "dgp1"
n <- 400
epsilons <- c(0.01, 0.05, 0.10, 0.20)
n_reps <- 100
tau <- 0.15
K <- 5

dgp_fn <- generate_data_dgp1

message("DGP: ", dgp_name)
message("Sample size: ", n)
message("Tolerances: ", paste(epsilons, collapse = ", "))
message("Replications per config: ", n_reps)
message("Total runs this batch: ", length(epsilons) * n_reps, "\n")

# Track memory
initial_mem <- as.numeric(system("ps -o rss= -p $$", intern = TRUE)) / 1024
message("Initial memory: ", round(initial_mem, 1), " MB\n")

batch_start <- Sys.time()

# Run each epsilon configuration
for (epsilon in epsilons) {
  message("\n--- Config: epsilon = ", epsilon, " ---")

  config_start <- Sys.time()

  # Run comparison
  result <- run_comparison(
    dgp_fn = dgp_fn,
    n = n,
    K = K,
    tau = tau,
    n_reps = n_reps,
    epsilon = epsilon,
    seed_start = 50000 + as.integer(epsilon * 10000)
  )

  config_elapsed <- as.numeric(difftime(Sys.time(), config_start, units = "secs"))

  # Save results (metrics only, no raw results)
  result_to_save <- list(
    config = data.frame(
      dgp = dgp_name,
      n = n,
      epsilon = epsilon,
      K = K,
      tau = tau,
      n_reps = n_reps
    ),
    fold_specific = result$fold_specific,
    rashomon = result$rashomon,
    oracle = result$oracle
  )

  saveRDS(result_to_save, file.path(results_dir,
          sprintf("result_%s_n%d_eps%.3f.rds", dgp_name, n, epsilon)))

  # Clear memory
  rm(result, result_to_save)
  gc(verbose = FALSE)

  current_mem <- as.numeric(system("ps -o rss= -p $$", intern = TRUE)) / 1024
  message(sprintf("  Config completed in %.1f sec", config_elapsed))
  message(sprintf("  Current memory: %.1f MB (delta: %.1f MB)",
                 current_mem, current_mem - initial_mem))
}

batch_elapsed <- as.numeric(difftime(Sys.time(), batch_start, units = "mins"))
final_mem <- as.numeric(system("ps -o rss= -p $$", intern = TRUE)) / 1024

message("\n=== BATCH 5 COMPLETE ===")
message("Batch time: ", round(batch_elapsed, 2), " minutes")
message("Final memory: ", round(final_mem, 1), " MB")
message("Memory increase: ", round(final_mem - initial_mem, 1), " MB\n")
